// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/auth/oauth_callback.tsx";
import * as $2 from "./routes/app/_middleware.ts";
import * as $3 from "./routes/app/admin/_middleware.ts";
import * as $4 from "./routes/app/admin/index.tsx";
import * as $5 from "./routes/app/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/login.tsx";
import * as $8 from "./routes/signout.ts";
import * as $$0 from "./islands/AuthCallbackRedirect.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/auth/oauth_callback.tsx": $1,
    "./routes/app/_middleware.ts": $2,
    "./routes/app/admin/_middleware.ts": $3,
    "./routes/app/admin/index.tsx": $4,
    "./routes/app/index.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/login.tsx": $7,
    "./routes/signout.ts": $8,
  },
  islands: {
    "./islands/AuthCallbackRedirect.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
